name: Bug report
description: bug report for OceanBase
title: "[Bug]: "
labels: [bug]
assignees:
  - caifeizhi
body:
  - type: checkboxes
    attributes:
      label: Please check the issue list first for the same bug 
      options:
        - label: I have checked and this bug is encountered for the first time.
          required: true
  - type: textarea
    attributes:
      label: Environment
      description: |
        Environment Details sometimes important 
      value: |
        - OB Version&commit_id or other module version&commit_id (e.g. observer V3.1.2 8b23a93):
        - Hardware parameter:OS type & Compliler & CPU etc. 
        - Others
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Fast Reproduce Steps(Required)
      description: Steps to reproduce what you encountered.
      render: markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Actual Behavior
      description: picture is allowed
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: Describe what you expected.
    validations:
      required: false
  - type: textarea
    attributes:
      label: other information
      description: |
        Environment Details sometimes important 
      value: |
        - Error Log or Core stack
        - Others
      render: markdown
    validations:
      required: false
